project_id = "bsndnraokqpuwvqzxtcu"

[functions.explain]
verify_jwt = true

[functions.snippet]
verify_jwt = true

[functions.regenerate]
verify_jwt = true

[functions.upload-diagram]
verify_jwt = true

[functions.create-guest-session]
verify_jwt = false

[functions.explain-code]
verify_jwt = false